apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: python-job-
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: python:3.11-slim
        command: [python, -c]
        args: ["print('Processing task in Kind...')"]
