FROM python:3.11-alpine
WORKDIR /app

# Install uv
RUN pip install --no-cache-dir uv

COPY pyproject.toml ./
RUN uv sync --no-install-project
EXPOSE 8000
CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
